# Generated by Django 5.1.1 on 2025-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='revised_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
