# Generated by Django 5.0.3 on 2025-12-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_revised_count_alter_word_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_date',
            field=models.DateField(auto_now_add=True, default='2025-12-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='need_improvement',
            field=models.BooleanField(default=False),
        ),
    ]
